### ISSUE TITLE
Research i18n in Next

### ISSUE THREAD

**Issue by triszt4n** [simonyiszk/simonyi-web-next#18]
If it's too hard, don't put priority on this issue yet

**Comment by triszt4n** [comment]
The big challenge is integrating this with MDX

**Comment by perryd01** [comment]
this was used for konf-web-2023 at the beginning: [next-i18next](https://github.com/i18next/next-i18next)

**Comment by gergoradeczki** [comment]
https://next-intl-docs.vercel.app/
